# Generated by Django 2.2.1 on 2019-06-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190628_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
