# Generated by Django 2.2.2 on 2019-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190628_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listenname',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='readname',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='watchname',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
