# Generated by Django 2.2.2 on 2019-06-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190629_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listenname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='readname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchname',
        ),
    ]
